# OpenNFT default configuration file
---

cglm_ar1: True
a_ar1: 0.2
iglm_ar1: True
shmem_file_names:
  - mc_ts
  - mosaic
  - epi_volume
  - stat_volume
  - rtqa_volume
  - orth_view_t
  - orth_view_c
  - orth_view_s
  - time_series
  - nfb
use_gui: True
use_roi: False
max_roi_name_length: 6
plot_grid_alpha: 0.7
roi_plot_width: 2.0
muster_y_limits: [-32767, 32768]
muster_plot_alpha: 50
donot_use_qfile_native_dialog: False

use_rtqa: True
use_iglm: True

dicom_siemens_xa30: False

is_zero_padding: False
nr_zero_pad_vol: False

auto_rtqa: False
use_epi_template: False

is_regr_iglm: True

is_high_pass: True
is_motion_regr: True
is_lin_regr: True

use_ptb: False

