# OpenNFT default configuration file
---

cglm_ar1: True
a_ar1: 0.2
iglm_ar1: True
shmem_file_names:
  - mc_ts
  - mosaic
  - epi_volume
  - stat_volume
  - rtqa_volume
  - orth_view_t
  - orth_view_c
  - orth_view_s
use_gui: False
use_roi: False